/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  IsBoolean,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { ChatUpdateManyWithoutRoomsInput } from "./ChatUpdateManyWithoutRoomsInput";
import { PlaylistUpdateManyWithoutRoomsInput } from "./PlaylistUpdateManyWithoutRoomsInput";

@InputType()
class RoomUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  lastActivityAt?: Date | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isActive?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  createdBy?: string | null;

  @ApiProperty({
    required: false,
    type: () => ChatUpdateManyWithoutRoomsInput,
  })
  @ValidateNested()
  @Type(() => ChatUpdateManyWithoutRoomsInput)
  @IsOptional()
  @Field(() => ChatUpdateManyWithoutRoomsInput, {
    nullable: true,
  })
  chats?: ChatUpdateManyWithoutRoomsInput;

  @ApiProperty({
    required: false,
    type: () => PlaylistUpdateManyWithoutRoomsInput,
  })
  @ValidateNested()
  @Type(() => PlaylistUpdateManyWithoutRoomsInput)
  @IsOptional()
  @Field(() => PlaylistUpdateManyWithoutRoomsInput, {
    nullable: true,
  })
  playlists?: PlaylistUpdateManyWithoutRoomsInput;
}

export { RoomUpdateInput as RoomUpdateInput };
