/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ChatUpdateManyWithoutUsersInput } from "./ChatUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { PlaylistUpdateManyWithoutUsersInput } from "./PlaylistUpdateManyWithoutUsersInput";
import { FavoriteUpdateManyWithoutUsersInput } from "./FavoriteUpdateManyWithoutUsersInput";
import { FriendUpdateManyWithoutUsersInput } from "./FriendUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  avatar?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  friendsCount?: number | null;

  @ApiProperty({
    required: false,
    type: () => ChatUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ChatUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ChatUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  chats?: ChatUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => PlaylistUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PlaylistUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PlaylistUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  playlists?: PlaylistUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => FavoriteUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => FavoriteUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => FavoriteUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  favorites?: FavoriteUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => FriendUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => FriendUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => FriendUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  friends?: FriendUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
